# Use Nginx to serve the frontend
FROM nginx:alpine

# Copy static HTML file to Nginx directory
COPY frontend/index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
